DROP DATABASE IF EXISTS recipes_db;
CREATE DATABASE recipes_db;

\c recipes_db;

CREATE TABLE recipes (
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR,
  STYLE VARCHAR,
  INGREDIENTS VARCHAR,
  PROCESS VARCHAR,
  CREATE_DATE timestamp DEFAULT CURRENT_TIMESTAMP
);